# Generated by Django 6.0.5 on 2026-05-24 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=200)),
                ("state", models.CharField(max_length=2)),
                ("state_full", models.CharField(blank=True, max_length=100)),
                ("metro_area", models.CharField(blank=True, max_length=200)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("population", models.IntegerField(blank=True, null=True)),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "ordering": ["state", "city"],
            },
        ),
        migrations.CreateModel(
            name="Procedure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "cpt_code",
                    models.CharField(blank=True, help_text="CPT code", max_length=20),
                ),
                ("hcpcs_code", models.CharField(blank=True, max_length=20)),
                ("drg_code", models.CharField(blank=True, max_length=20)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Imaging, Surgery, Dental, etc.",
                        max_length=200,
                    ),
                ),
                ("subcategory", models.CharField(blank=True, max_length=200)),
                ("is_elective", models.BooleanField(default=False)),
                ("is_cash_pay_common", models.BooleanField(default=False)),
                (
                    "national_average_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "national_median_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "cost_range_low",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "cost_range_high",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("search_volume_estimate", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProviderType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Vertical",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "tier",
                    models.IntegerField(
                        default=1,
                        help_text="Launch tier: 1=launch, 2=fast follow, 3=expansion, 4=long-term",
                    ),
                ),
                ("sort_order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("slug", models.SlugField(unique=True)),
                ("legal_name", models.CharField(blank=True, max_length=500)),
                ("address", models.TextField(blank=True)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("website", models.URLField(blank=True)),
                (
                    "npi_number",
                    models.CharField(
                        blank=True,
                        help_text="National Provider Identifier",
                        max_length=20,
                    ),
                ),
                ("license_number", models.CharField(blank=True, max_length=100)),
                ("license_state", models.CharField(blank=True, max_length=2)),
                ("license_status", models.CharField(blank=True, max_length=50)),
                ("license_verified_date", models.DateField(blank=True, null=True)),
                ("board_certified", models.BooleanField(null=True)),
                (
                    "accreditation",
                    models.CharField(
                        blank=True,
                        help_text="AAAHC, Joint Commission, etc.",
                        max_length=200,
                    ),
                ),
                (
                    "ownership_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("independent", "Independent"),
                            ("hospital_system", "Hospital System"),
                            ("private_equity", "Private Equity Owned"),
                            ("physician_group", "Physician Group"),
                            ("nonprofit", "Nonprofit"),
                            ("government", "Government"),
                            ("franchise", "Franchise"),
                        ],
                        max_length=50,
                    ),
                ),
                ("parent_organization", models.CharField(blank=True, max_length=500)),
                (
                    "pe_firm",
                    models.CharField(
                        blank=True,
                        help_text="Private equity firm if applicable",
                        max_length=300,
                    ),
                ),
                (
                    "cms_star_rating",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=2, null=True
                    ),
                ),
                (
                    "patient_satisfaction_score",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("employee_count", models.IntegerField(blank=True, null=True)),
                ("year_established", models.IntegerField(blank=True, null=True)),
                (
                    "beds",
                    models.IntegerField(
                        blank=True, help_text="For hospitals", null=True
                    ),
                ),
                (
                    "transparency_compliant",
                    models.BooleanField(
                        help_text="CMS price transparency compliance", null=True
                    ),
                ),
                (
                    "transparency_score",
                    models.IntegerField(blank=True, help_text="0-100", null=True),
                ),
                ("description", models.TextField(blank=True)),
                ("summary_line", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="healthcare.location",
                    ),
                ),
                (
                    "provider_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="healthcare.providertype",
                    ),
                ),
                (
                    "verticals",
                    models.ManyToManyField(blank=True, to="healthcare.vertical"),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PricingRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cash_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "insured_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "chargemaster_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "negotiated_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "insurer_name",
                    models.CharField(
                        blank=True, help_text="For negotiated rates", max_length=200
                    ),
                ),
                (
                    "price_type",
                    models.CharField(
                        choices=[
                            ("cms_published", "CMS Published"),
                            ("provider_website", "Provider Website"),
                            ("crowdsourced", "Crowdsourced"),
                            ("estimated", "Estimated"),
                            ("negotiated", "Negotiated Rate"),
                        ],
                        default="estimated",
                        max_length=30,
                    ),
                ),
                (
                    "confidence",
                    models.CharField(
                        choices=[
                            ("high", "High — CMS or verified source"),
                            ("medium", "Medium — provider website or aggregator"),
                            ("low", "Low — estimated or crowdsourced"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "percentile_rank",
                    models.IntegerField(
                        blank=True,
                        help_text="Price percentile vs regional peers",
                        null=True,
                    ),
                ),
                (
                    "vs_regional_median",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Multiplier vs regional median. 1.0 = average, 2.0 = 2x median",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("source_url", models.URLField(blank=True)),
                ("source_name", models.CharField(blank=True, max_length=200)),
                ("last_verified", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "procedure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing_records",
                        to="healthcare.procedure",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing_records",
                        to="healthcare.provider",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="DataSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_name", models.CharField(max_length=200)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("cms_mrf", "CMS Machine-Readable File"),
                            ("cms_quality", "CMS Quality Data"),
                            ("state_board", "State Medical/Dental Board"),
                            ("court_records", "Court Records"),
                            ("provider_website", "Provider Website"),
                            ("review_platform", "Review Platform"),
                            ("user_submitted", "User Submitted"),
                        ],
                        max_length=30,
                    ),
                ),
                ("source_url", models.URLField(blank=True)),
                ("last_checked", models.DateField()),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_sources",
                        to="healthcare.provider",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SafetyEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField()),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("malpractice", "Malpractice Action"),
                            ("sanction", "Sanction/Disciplinary"),
                            ("license_action", "License Action"),
                            ("inspection_failure", "Inspection Failure"),
                            ("patient_death", "Patient Death Report"),
                            ("fda_warning", "FDA Warning"),
                            ("safety_violation", "Safety Violation"),
                            ("lawsuit", "Lawsuit"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("serious", "Serious"),
                            ("moderate", "Moderate"),
                            ("minor", "Minor"),
                        ],
                        max_length=20,
                    ),
                ),
                ("source_agency", models.CharField(blank=True, max_length=200)),
                ("source_url", models.URLField(blank=True)),
                (
                    "penalty_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="safety_events",
                        to="healthcare.provider",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.AddField(
            model_name="procedure",
            name="verticals",
            field=models.ManyToManyField(blank=True, to="healthcare.vertical"),
        ),
        migrations.CreateModel(
            name="InsuranceAcceptance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("insurer_name", models.CharField(max_length=200)),
                ("plan_name", models.CharField(blank=True, max_length=200)),
                ("in_network", models.BooleanField(default=True)),
                ("verified_date", models.DateField(blank=True, null=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insurance_acceptance",
                        to="healthcare.provider",
                    ),
                ),
            ],
            options={
                "unique_together": {("provider", "insurer_name", "plan_name")},
            },
        ),
    ]
