# Generated by Django 6.0.5 on 2026-05-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthcare", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="provider",
            name="slug",
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
