# Generated by Django 6.0.5 on 2026-05-28 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthcare", "0004_claimrequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cash_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "insured_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("price_type", models.CharField(default="published", max_length=30)),
                ("source_name", models.CharField(blank=True, max_length=300)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "procedure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_snapshots",
                        to="healthcare.procedure",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_snapshots",
                        to="healthcare.provider",
                    ),
                ),
            ],
            options={
                "ordering": ["-recorded_at"],
                "indexes": [
                    models.Index(
                        fields=["provider", "procedure", "recorded_at"],
                        name="healthcare__provide_e90fad_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProviderSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(max_length=100)),
                ("old_value", models.TextField(blank=True)),
                ("new_value", models.TextField(blank=True)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                ("source", models.CharField(blank=True, max_length=200)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metadata_snapshots",
                        to="healthcare.provider",
                    ),
                ),
            ],
            options={
                "ordering": ["-changed_at"],
                "indexes": [
                    models.Index(
                        fields=["provider", "changed_at"],
                        name="healthcare__provide_04327a_idx",
                    ),
                    models.Index(
                        fields=["field_name", "changed_at"],
                        name="healthcare__field_n_6bd5f7_idx",
                    ),
                ],
            },
        ),
    ]
