# Generated by Django 6.0.5 on 2026-05-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthcare", "0005_pricesnapshot_providersnapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="display_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
