# Generated by Django 6.0.5 on 2026-05-30 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("healthcare", "0006_provider_display_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="provider",
            name="display_name",
        ),
    ]
