# Generated by Django 6.0.5 on 2026-05-30 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthcare", "0007_remove_provider_display_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="procedure",
            name="display_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
