# Generated by Django 6.0.5 on 2026-06-03 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthcare", "0008_procedure_display_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricingrecord",
            name="price_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("submitted_charge", "Submitted Charge"),
                    ("negotiated_rate", "Negotiated Rate"),
                    ("gross_charge", "Gross Charge"),
                    ("cash_price", "Cash Price"),
                    ("medicare_rate", "Medicare Rate"),
                ],
                default="submitted_charge",
                max_length=30,
            ),
        ),
    ]
