# Generated by Django 6.0.5 on 2026-06-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthcare", "0010_alter_pricingrecord_price_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricingrecord",
            name="billing_component",
            field=models.CharField(
                blank=True,
                choices=[
                    ("professional", "Professional"),
                    ("technical", "Technical/Facility"),
                    ("global", "Global (Both)"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
