# Generated by Django 6.0.5 on 2026-06-25 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthcare", "0011_pricingrecord_billing_component"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcedureMedian",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("median_price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "p25",
                    models.DecimalField(decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "p75",
                    models.DecimalField(decimal_places=2, max_digits=12, null=True),
                ),
                ("provider_count", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="procedure_medians",
                        to="healthcare.location",
                    ),
                ),
                (
                    "procedure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medians",
                        to="healthcare.procedure",
                    ),
                ),
                (
                    "provider_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="procedure_medians",
                        to="healthcare.providertype",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["procedure", "location", "provider_type"],
                        name="healthcare__procedu_375f59_idx",
                    )
                ],
                "unique_together": {("procedure", "location", "provider_type")},
            },
        ),
    ]
