# Generated by Django 6.0.5 on 2026-06-30 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthcare", "0012_proceduremedian"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="is_individual",
            field=models.BooleanField(default=False),
        ),
    ]
