# Generated by Django 6.0.5 on 2026-07-01 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthcare", "0013_provider_is_individual"),
    ]

    operations = [
        migrations.AddField(
            model_name="procedure",
            name="national_avg",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="procedure",
            name="national_avg_medicare",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="procedure",
            name="national_median",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="procedure",
            name="national_p25",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="procedure",
            name="national_p5",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="procedure",
            name="national_p75",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="procedure",
            name="national_p95",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="procedure",
            name="national_provider_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="procedure",
            name="national_record_count",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
