# Generated by Django 6.0.5 on 2026-07-09 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthcare", "0014_procedure_national_avg_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="procedure",
            name="by_type_json",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="procedure",
            name="top_cities_json",
            field=models.TextField(blank=True, null=True),
        ),
    ]
