# Generated by Django 6.0.5 on 2026-07-24 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthcare", "0015_procedure_by_type_json_procedure_top_cities_json"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceAlertSignup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("procedure_slug", models.CharField(default="botox", max_length=100)),
                ("city_slug", models.CharField(default="miami-fl", max_length=100)),
                ("source_page", models.CharField(blank=True, max_length=40)),
                ("visitor_id", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("email", "procedure_slug", "city_slug")},
            },
        ),
        migrations.CreateModel(
            name="ConsumerLead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("procedure_slug", models.CharField(default="botox", max_length=100)),
                ("city_slug", models.CharField(default="miami-fl", max_length=100)),
                (
                    "provider_name",
                    models.CharField(
                        blank=True,
                        help_text="Denormalized snapshot of the provider name at lead time.",
                        max_length=500,
                    ),
                ),
                ("contact_name", models.CharField(max_length=200)),
                ("contact_email", models.EmailField(max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=40)),
                (
                    "variant_interest",
                    models.CharField(
                        blank=True,
                        help_text="Which Botox variant / area the shopper asked about.",
                        max_length=200,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                (
                    "source_page",
                    models.CharField(
                        blank=True, help_text="hub | cheapest | provider", max_length=40
                    ),
                ),
                (
                    "visitor_id",
                    models.CharField(
                        blank=True,
                        help_text="First-party anonymous cookie id, for funnel attribution.",
                        max_length=64,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("sold", "Sold to provider"),
                            ("spam", "Spam"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consumer_leads",
                        to="healthcare.provider",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["procedure_slug", "city_slug", "created_at"],
                        name="healthcare__procedu_5d708c_idx",
                    ),
                    models.Index(
                        fields=["provider", "created_at"],
                        name="healthcare__provide_64c235_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WedgeEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("page_view", "Page View"),
                            ("lead_open", "Lead Form Opened"),
                            ("lead_submit", "Lead Submitted"),
                            ("email_signup", "Email Signup"),
                            ("claim_click", "Claim Clicked"),
                            ("claim_submit", "Claim Submitted"),
                            ("provider_click", "Provider Clicked"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "page",
                    models.CharField(
                        blank=True, help_text="hub | cheapest | provider", max_length=40
                    ),
                ),
                ("procedure_slug", models.CharField(blank=True, max_length=100)),
                ("city_slug", models.CharField(blank=True, max_length=100)),
                ("provider_slug", models.CharField(blank=True, max_length=200)),
                ("visitor_id", models.CharField(blank=True, max_length=64)),
                ("referrer", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wedge_events",
                        to="healthcare.provider",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "created_at"],
                        name="healthcare__event_t_ce1d02_idx",
                    ),
                    models.Index(
                        fields=["procedure_slug", "city_slug", "event_type"],
                        name="healthcare__procedu_fdb64b_idx",
                    ),
                    models.Index(
                        fields=["visitor_id", "event_type"],
                        name="healthcare__visitor_1dcd7b_idx",
                    ),
                ],
            },
        ),
    ]
