# Generated by Django 6.0.5 on 2026-08-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthcare", "0016_pricealertsignup_consumerlead_wedgeevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="claimrequest",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="claimrequest",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="claimrequest",
            name="tier",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("verified", "Verified (free)"),
                    ("paid_basic", "Paid — Featured"),
                    ("paid_premium", "Paid — Premium"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="claimrequest",
            name="tier_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
