# Generated by Django 6.0.5 on 2026-08-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthcare", "0017_claimrequest_stripe_customer_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wedgeevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("page_view", "Page View"),
                    ("lead_open", "Lead Form Opened"),
                    ("lead_submit", "Lead Submitted"),
                    ("email_signup", "Email Signup"),
                    ("claim_click", "Claim Clicked"),
                    ("claim_submit", "Claim Submitted"),
                    ("provider_click", "Provider Clicked"),
                    ("phone_click", "Phone Clicked"),
                    ("website_click", "Website Clicked"),
                ],
                max_length=30,
            ),
        ),
    ]
