# Generated by Django 6.0.5 on 2026-08-07 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthcare", "0018_alter_wedgeevent_event_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "logo",
                    models.URLField(
                        blank=True, help_text="URL to logo image (no upload yet)"
                    ),
                ),
                ("cover_image", models.URLField(blank=True)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text='"About your pricing" — one paragraph'
                    ),
                ),
                ("payment_cash", models.BooleanField(default=False)),
                ("payment_credit", models.BooleanField(default=False)),
                ("payment_hsa", models.BooleanField(default=False)),
                ("payment_fsa", models.BooleanField(default=False)),
                ("payment_carecredit", models.BooleanField(default=False)),
                ("payment_other", models.CharField(blank=True, max_length=200)),
                ("financing_available", models.BooleanField(default=False)),
                ("financing_details", models.CharField(blank=True, max_length=300)),
                (
                    "languages",
                    models.CharField(
                        blank=True, help_text="Comma-separated", max_length=200
                    ),
                ),
                (
                    "equipment_notes",
                    models.CharField(
                        blank=True, help_text='e.g. "3T MRI, Open MRI"', max_length=300
                    ),
                ),
                ("preparation_instructions", models.TextField(blank=True)),
                (
                    "hours_json",
                    models.TextField(blank=True, help_text="JSON string for hours"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="healthcare.provider",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProviderProcedureDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("includes_consultation", models.BooleanField(blank=True, null=True)),
                ("includes_interpretation", models.BooleanField(blank=True, null=True)),
                ("includes_facility_fee", models.BooleanField(blank=True, null=True)),
                ("includes_anesthesia", models.BooleanField(blank=True, null=True)),
                ("includes_followup", models.BooleanField(blank=True, null=True)),
                ("financing_available", models.BooleanField(blank=True, null=True)),
                (
                    "turnaround",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("same_day", "Same day"),
                            ("24_hours", "24 hours"),
                            ("48_hours", "48 hours"),
                            ("3_5_days", "3–5 days"),
                            ("1_week", "1 week"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("self_pay_discount", models.BooleanField(blank=True, null=True)),
                ("price_guaranteed", models.BooleanField(blank=True, null=True)),
                (
                    "good_faith_estimate_available",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "provider_notes",
                    models.TextField(
                        blank=True, help_text='"About your pricing" — free text'
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "procedure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_details",
                        to="healthcare.procedure",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="procedure_details",
                        to="healthcare.provider",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["provider"], name="healthcare__provide_a007d6_idx"
                    )
                ],
                "unique_together": {("provider", "procedure")},
            },
        ),
    ]
