import os
"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure--5*)6q*-am!z@%_rxo6z_i#)u^7eezq_a*%oi+uq%n^cbcxxgv"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sitemaps",
    "django.contrib.humanize",
    "healthcare",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static_src")]

import os
import dj_database_url

if os.environ.get('RAILWAY_ENVIRONMENT'):
    DEBUG = os.environ.get('DEBUG', 'False') == 'True'
    ALLOWED_HOSTS = ['*']
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

    MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')
    STORAGES = {
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }

    DATABASE_URL = os.environ.get('DATABASE_URL')
    if DATABASE_URL:
        DATABASES['default'] = dj_database_url.config(default=DATABASE_URL)

    CSRF_TRUSTED_ORIGINS = [
        'https://*.railway.app',
        'https://zenthir.com',
        'https://www.zenthir.com',
    ]
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    SESSION_COOKIE_SAMESITE = 'Lax'
    CSRF_COOKIE_SECURE = True

    SECRET_KEY = os.environ.get('SECRET_KEY', SECRET_KEY)


# Stripe
STRIPE_SECRET_KEY = os.environ.get('STRIPE_SECRET_KEY', '')
STRIPE_PUBLISHABLE_KEY = os.environ.get('STRIPE_PUBLISHABLE_KEY', '')
STRIPE_PRICE_ID = os.environ.get('STRIPE_PRICE_ID', '')  # Legacy, kept for compat
# Signing secret for the provider-subscription webhook (whsec_...). Set on
# Railway AFTER the endpoint is registered in the Stripe dashboard.
STRIPE_WEBHOOK_SECRET = os.environ.get('STRIPE_WEBHOOK_SECRET', '')
STRIPE_PRICES = {
    'verified_monthly': 'price_1Twp549jUznFp3SxUP3FigSh',
    'verified_yearly': 'price_1Twp549jUznFp3Sx1AiXCtF4',
    'market_intel_monthly': 'price_1Twp6c9jUznFp3SxSIh62kRU',
    'market_intel_yearly': 'price_1Twp769jUznFp3Sxjv5DsMOa',
    'founding_provider': 'price_1Twp9k9jUznFp3SxJCfEVHWf',
    'competitor_report': 'price_1TwpA49jUznFp3SxVKVtqscs',
    'premium_report': 'price_1TwpAS9jUznFp3SxKA3qGLJk',
    'bill_audit': 'price_1TwpAj9jUznFp3SxF6PL9nzy',
}

# --- Provider subscription plans (Claim -> Verified -> Paid) -----------------
# Maps a plan key (?plan= on the upgrade route) to the Stripe price to charge
# and the ClaimRequest.tier the successful subscription grants. `price_key`
# indexes STRIPE_PRICES so we never hardcode a raw price id here. Leads stay
# free on 'verified'; these tiers unlock enhanced/featured treatment.
PROVIDER_PLANS = {
    'featured': {
        'price_key': 'verified_monthly',   # the $99/mo Featured listing
        'tier': 'paid_basic',
        'label': 'Featured',
        'price_display': '$99/mo',
    },
    'premium': {
        'price_key': 'market_intel_monthly',
        'tier': 'paid_premium',
        'label': 'Premium',
        'price_display': '',  # surfaced only after price is confirmed
    },
}

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'zenthir-cache',
        'TIMEOUT': 86400,
        'OPTIONS': {
            'MAX_ENTRIES': 5000,
        }
    }
}
